# Generated by Django 5.1 on 2024-08-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_contacts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='members',
        ),
    ]
