# Generated by Django 5.1 on 2024-10-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='members',
            field=models.TextField(default=''),
        ),
    ]
