# Generated by Django 5.1 on 2024-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_tasks_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='members',
            field=models.TextField(default='[]'),
        ),
    ]
